
debug = true

[enum]
remove_prefix = true
remove_unspecified_entry = true

[output]
path = "openapi"

[mikros]
use_outbound_messages = true
use_inbound_messages = true
settings_filename = "protoc-gen-mikros-extensions.toml"
keep_main_module_file_prefix = true
